### ISSUE TITLE
Incorrect dates and new posts not displayed

### ISSUE THREAD

**Issue by xavierroy** [aaronpk/Teacup#9]
Posts have  a Jan 1, 1970 timestamp: see https://teacup.p3k.io/xavierroy.com/13498. 
Also, newer posts are not displayed in https://teacup.p3k.io/xavierroy.com .

**Comment by aaronpk** [comment]
What browser are you using? This must have something to do with the browser not sending the right value in the date field.

**Comment by xavierroy** [comment]
Tried with Chrome Version 63.0.3239.132 (Official Build) (64-bit) and Firefox Quantum 57.0.3 (64-bit)

**Comment by aaronpk** [comment]
Looks like it was an issue with half-hour timezones! Should be fixed in 32894d8917f4cbfd10f9deef2b31cf3506a2971b. Can you check again?

**Comment by xavierroy** [comment]
Think it still doesn't work as expected. Posts are not showing up on my website.
